# Generated by Django 3.0.4 on 2020-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('href', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('upload', models.DateTimeField()),
            ],
        ),
    ]
